#include <cstdint>
#include <string>
#include <cstdio>
#include <vector>

#if defined(__LINUX__) | defined(__linux__)
#include <X11/Xlib.h>
#elif defined(WIN32)
#include <Windows.h>
#include <Windowsx.h>
#endif // defined(__LINUX__) | defined(__linux__)

typedef void (*WindowResizeCallback)(void*);

static std::string UTF16ToUTF8(const std::wstring &s)
{
    const int size = ::WideCharToMultiByte(CP_UTF8, 0, s.c_str(), -1, NULL, 0, 0, NULL);

    std::vector<char> buf(size);
    ::WideCharToMultiByte(CP_UTF8, 0, s.c_str(), -1, &buf[0], size, 0, NULL);

    return std::string(&buf[0]);
}

// Virtual-Key Codes taken from MSDN.
// These are based on codes generated by a Keyboard, so Linux version is identical.
// enum is not strongly typed due to implicit conversion from KeyCode to int.
enum KeyCode
{
    Backspace = 0x08,
    Tab,
    // here 0x0A-0x0B are reserved, 0x0C is unused CLEAR
    Enter = 0x0D,
    // 0x0E - 0x0F reserved
    Shift = 0x10,
    Control,
    Alt,
    Pause,
    CapsLock,
    // 0x15 - 0x1A are IME-related keys, not needed by us
    EscapeBtn = 0x1B,
    // 0x1C - 0x1F are IME-related keys
    Space = 0x20,
    PageUp,
    PageDown,
    End,
    Home,
    Left,
    Up,
    Right,
    Down,
    Select,
    Print,
    Execute,
    PrintScreen,
    Insert,
    Delete,
    // regular chars does not require key codes - use apostrophes to catch them
    WinLeft = 0x5B,
    WinRight,
    // 0x5D - Apps Key (unused), 0x5E - Reserved, 0x5F - PC Sleep key
    Numpad0 = 0x60,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadMulitply,
    NumpadAdd,
    NumpadSeparator,
    NumpadSubtract,
    NumpadDecimal,
    NumpadDivide,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    // 0x88-0x8F - unassigned keys
    NumLock = 0x90,
    ScrollLock,
    // 0x92-0x96 - OEM-specific, 0x97-0x9F - unassigned
    ShiftLeft= 0xA0,
    ShiftRight,
    ControlLeft,
    ControlRight,
    MenuLeft,
    MenuRight,
    // rest of the keys are media controllers and OEM/IME special
};

/**
 * Simple UI windows class.
 */
class WindowManager
{
private:
#if defined(WIN32)
    static LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam);
    HWND mHandle;
    HINSTANCE mInstance;
    int mLeft;
    int mTop;
    wchar_t mWndClass[48];
#elif defined(__LINUX__) | defined(__linux__)
    static ::Display* mDisplay;
    ::Window mWindow;
    ::Window mRoot;
    static bool mWindowError;
    static int ErrorHandler(::Display* dpy, XErrorEvent *error);
#else //...
#error "Target not supported!"
#endif // defined(WIN32)

    bool mClosed;
    bool mFullscreen;
    uint32_t mWidth;
    uint32_t mHeight;
    std::string mTitle;

    bool mMouseButtons[3];
    int mMouseDownX[3];
    int mMouseDownY[3];

    bool mKeys[256];

    // used by renderer
    WindowResizeCallback mResizeCallback;
    void* mResizeCallbackUserData;

    void LostFocus();
    void MouseDown(uint32_t button, int x, int y);
    void MouseUp(uint32_t button);
    void MouseMove(int x, int y);

    WindowManager(const WindowManager&);
    WindowManager& operator= (const WindowManager&) = delete;

public:
    WindowManager();
    ~WindowManager();

    bool Open();
    bool Close();

    void* GetHandle() const;
    void GetSize(uint32_t& width, uint32_t& height) const;
    float GetAspectRatio() const;
    bool GetFullscreenMode() const;

    bool IsMouseButtonDown(uint32_t button) const;
    bool IsKeyPressed(int key) const;

    void SetSize(uint32_t hidth, uint32_t height);
    void SetFullscreenMode(bool enabled);
    void SetTitle(const char* title);

    // WARINING: only engine should call this function
    void SetResizeCallback(WindowResizeCallback func, void* userData);

    void ProcessMessages();
    bool IsClosed() const;
    bool HasFocus() const;

    // callbacks
    virtual void OnClose();
    virtual void OnResize(uint32_t width, uint32_t height);
    virtual void OnKeyPress(int key);
    virtual void OnScroll(int delta);
    virtual void OnMouseDown(uint32_t button, int x, int y);
    virtual void OnMouseMove(int x, int y, int deltaX, int deltaY);
    virtual void OnMouseUp(uint32_t button);
};
